Presentation/Controllers/StockController.cs
using Microsoft.AspNetCore.Mvc;
using StockApp.Application;
using StockApp.Core;
using System.Collections.Generic;

namespace StockApp.WebUI.Controllers
{
    public class StockController : Controller
    {
        private readonly IGetStocksByExchangeUseCase _getStocksByExchangeUseCase;
        private readonly IGetStockDetailsUseCase _getStockDetailsUseCase;

        public StockController(IGetStocksByExchangeUseCase getStocksByExchangeUseCase, IGetStockDetailsUseCase getStockDetailsUseCase)
        {
            _getStocksByExchangeUseCase = getStocksByExchangeUseCase;
            _getStockDetailsUseCase = getStockDetailsUseCase;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult StockMenu(string exchangeCode)
        {
            List<Stock> stocks = _getStocksByExchangeUseCase.Execute(exchangeCode);
            return View(stocks);
        }

        public IActionResult StockDetails(string stockCode)
        {
            Stock stock = _getStockDetailsUseCase.Execute(stockCode);
            return View(stock);
        }
    }
}

Presentation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - My ASP.NET Core Application</title>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="chat-container">

        <div class="select-message">
            <img src="~/images/robot-head.png" alt="Robot Head" class="robot-head">
            <p>Hello! Welcome to LSEG chatbot.</p>

        </div>
     
        <div class="container">
            @RenderBody()
        </div>
    </div>
</body>
</html>

Presentation/Views/Stock/Index.cshtml
@{
    ViewData["Title"] = "Home Menu";
}
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="select-message">
    <p>Please select a Stock Exchange.</p>
</div>

<h2></h2>
<ul class="stock-exchange-list">
    <li><a href="@Url.Action("StockMenu", "Stock", new { exchangeCode = "LSE" })">LSE</a></li>
    <li><a href="@Url.Action("StockMenu", "Stock", new { exchangeCode = "NASDAQ" })">NASDAQ</a></li>
    <li><a href="@Url.Action("StockMenu", "Stock", new { exchangeCode = "NYSE" })">NYSE</a></li>
</ul>

Presentation/Views/Stock/StockDetails.cshtml
@model StockApp.Core.Stock

@{
    ViewData["Title"] = "Stock Details";
}

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="select-message">
    <p>Here is the stock price.</p>
</div>

<h2>@Model.StockName</h2>
<p>Price: @Model.Price</p>
<ul class="stock-exchange-list">
    <a href="@Url.Action("StockMenu", "Stock", new { exchangeCode = "LSE" })"> < Back to Stock Menu</a>
    <br>
    <a href="@Url.Action("Index", "Stock")" class="back-link"> <br> < Back to Home Menu  </a>
</ul>

Presentation/Views/Stock/StockMenu.cshtml
@model IEnumerable<StockApp.Core.Stock>

@{
    ViewData["Title"] = "Stock Menu";
}
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="select-message">
    <p>Please select a stock.</p>
</div>

<ul class="stock-exchange-list" ">
    @foreach (var stock in Model)
    {
        <li><a href="@Url.Action("StockDetails", "Stock", new { stockCode = stock.Code })">@stock.StockName</a></li>
    }
    <h1> </h1>
    <a href="@Url.Action("Index", "Stock")" class="back-link"> < Back to Home Menu</a>
</ul>